import {readFile, unlink, writeFile} from 'node:fs/promises';
import assert from 'node:assert';
import {fileURLToPath} from 'node:url';
import {packageExtract} from '../lib/index.js';
import path from 'node:path';
import {test} from 'node:test';
import {version} from '../package.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

test('packageExtract', async() => {
  let out = null;
  const opts = {
    log(str) {
      out = str;
    },
    output: '-',
  };
  await packageExtract(opts, ['name', 'homepage']);
  assert.equal(out, `\
// Generated by package-extract v${version}
// Do not modify by hand.

export const name = 'package-extract'
export const homepage = 'https://github.com/hildjj/package-extract'
`);
  out = null;
  await packageExtract(opts, []);
  assert.equal(out, `\
// Generated by package-extract v${version}
// Do not modify by hand.

export const version = '${version}'
`);
  out = null;
  await assert.rejects(() => packageExtract(opts, ['field does not exist']));
  assert.equal(out, null);

  const output = path.join(__dirname, 'testOutput.js');
  await packageExtract({...opts, output});
  await unlink(output);
});

test('commonJS', async() => {
  let out = null;
  const opts = {
    log(str) {
      out = str;
    },
    output: '-',
    commonJS: true,
  };
  await packageExtract(opts, []);
  assert.equal(out, `\
// Generated by package-extract v${version}
// Do not modify by hand.

'use strict'

exports.version = '${version}'
`);
});

test('indent tab', async() => {
  let out = null;
  const opts = {
    log(str) {
      out = str;
    },
    output: '-',
    indent: -1,
    double: true,
  };
  await packageExtract(opts, ['engines']);
  assert.match(out, /engines/);
});

test('indent zero', async() => {
  let out = null;
  const opts = {
    log(str) {
      out = str;
    },
    output: '-',
    indent: 0,
    semi: true,
  };
  await packageExtract(opts, ['keywords']);
  assert.match(out, /keywords/);
});

test('regex', async() => {
  const output = new URL('./fixtures/index.html', import.meta.url);
  const orig = await readFile(output, 'utf8');
  await packageExtract({
    output,
    regex: '(?<=https:\\/\\/unpkg.com\\/peggy@)(?<version>\\d+\\.\\d+\\.\\d+)(?=\\/browser\\/peggy\\.min\\.js)',
  });
  let mod = await readFile(output, 'utf8');
  assert.match(mod, new RegExp(version.replace(/\./g, '\\.')));

  await packageExtract({
    output,
    regex: '(?<=https:\\/\\/unpkg.com\\/peggy@)(?<__UNKNOWN_FIELD__>\\d+\\.\\d+\\.\\d+)(?=\\/browser\\/peggy\\.min\\.js)',
  });
  mod = await readFile(output, 'utf8');
  assert.match(mod, new RegExp(version.replace(/\./g, '\\.')));

  await writeFile(output, orig);
});

test('unlessPreRelease', async() => {
  let out = '';
  const opts = {
    log(str) {
      out += str;
    },
    package: path.join(__dirname, 'fixtures', 'prerelease.json'),
    unlessPreRelease: true,
  };

  await packageExtract(opts);
  assert.equal(out, '');
});

test('unlessPreRelease invalid', async() => {
  let out = '';
  const opts = {
    log(str) {
      out += str;
    },
    package: path.join(__dirname, 'fixtures', 'invalidVersion.json'),
    unlessPreRelease: true,
  };

  await assert.rejects(() => packageExtract(opts));
  assert.equal(out, '');
});
