name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: '*'

jobs:
  build:
    strategy:
      matrix:
        node-version: [18, 20, 22, 23]
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Types
        run: npm run types
      - name: Lint
        if: matrix.os == 'ubuntu-latest'
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
